version: '2'
services:
  db:
    restart: always
    image: postgres:9.6.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=voat
    volumes:
      - ./postgres:/var/lib/postgresql
  application:
    build: ./application
    command: python3 /application/rest_server.py
    links:
      - db
    expose:
     - "8080"
    ports:
      - "8080:8080"
  nginx:
    restart: always
    build: ./nginx
    links:
      - application
    expose:
      - 80
    ports:
      - "8880:80"
